### ISSUE TITLE
[BUG]: fail in Single scene rendering

### ISSUE THREAD

**Issue by qiisun** [yinyunie/BlenderProc-3DFront#1]
Hi,

Thanks for your effort in visualization of 3D-front, but I met some bugs:

In the line,
https://github.com/yinyunie/BlenderProc-3DFront/blob/faa13d9f1292749b54a13e12e61acd50ca518c0d/examples/datasets/front_3d_with_improved_mat/render_dataset_improved_mat.py#L129

what is the `model_info_revised.json` in the 3d-future dataset. Since the origin 3d-future dataset only contains the `model_info.json` file, I just change the name of the file to enable the progress. Is my solution right ? Maybe I missed something.

**Comment by qiisun** [comment]
+ Bug in Single scene rendering

When I was run such script:

`
CUDA_VISIBLE_DEVICES=4,5,6,7 \
blenderproc run \
examples/datasets/front_3d_with_improved_mat/render_dataset_improved_mat.py \
examples/datasets/front_3d_with_improved_mat/3D-FRONT \
examples/datasets/front_3d_with_improved_mat/3D-FUTURE-model \
examples/datasets/front_3d_with_improved_mat/3D-FRONT-texture \
6a0e73bc-d0c4-4a38-bfb6-e083ce05ebe9.json \
resources/cctextures/ \
examples/datasets/front_3d_with_improved_mat/renderings
`

Initially, there were no encounters with any bugs.

![image](https://github.com/yinyunie/BlenderProc-3DFront/assets/55343765/277c37ed-fd7a-4fc9-b861-5c58b425962a)
![image](https://github.com/yinyunie/BlenderProc-3DFront/assets/55343765/d38ae6d1-97f2-4b8d-b988-3694bf5d11cb)
![image](https://github.com/yinyunie/BlenderProc-3DFront/assets/55343765/5ab25e49-d3db-4500-82e9-3b6addbce378)

![image](https://github.com/yinyunie/BlenderProc-3DFront/assets/55343765/0879195f-63e5-4e83-ae50-781393a0d188)

But when the Fra: num==101
the code failed, I have no idea to deal with it.
![image](https://github.com/yinyunie/BlenderProc-3DFront/assets/55343765/57be1cdb-2115-419f-bd84-86b1060fd738)

**Comment by yinyunie** [comment]
> Hi,
> 
> Thanks for your effort in visualization of 3D-front, but I met some bugs:
> 
> In the line,
> 
> https://github.com/yinyunie/BlenderProc-3DFront/blob/faa13d9f1292749b54a13e12e61acd50ca518c0d/examples/datasets/front_3d_with_improved_mat/render_dataset_improved_mat.py#L129
> 
> what is the `model_info_revised.json` in the 3d-future dataset. Since the origin 3d-future dataset only contains the `model_info.json` file, I just change the name of the file to enable the progress. Is my solution right ? Maybe I missed something.

Hi,

Thanks for pointing it out. I uploaded the `examples/datasets/front_3d_with_improved_mat/model_info_revised.json`, and updated the README. You basically need to move it to the 3D-FUTURE folder. Could you try again?

BTW,  before you re-render a scene that failed once before, you need to delete it in the `failed_scene_names.txt`, which is automatically generated in `examples/datasets/front_3d_with_improved_mat`. This strategy is to skip bad scene cases that are not renderable.

Thanks

**Comment by qiisun** [comment]
Thanks for your kind advice. I will try it soon and see whether there is other bugs.


> > Hi,
> > Thanks for your effort in visualization of 3D-front, but I met some bugs:
> > In the line,
> > https://github.com/yinyunie/BlenderProc-3DFront/blob/faa13d9f1292749b54a13e12e61acd50ca518c0d/examples/datasets/front_3d_with_improved_mat/render_dataset_improved_mat.py#L129
> > 
> > what is the `model_info_revised.json` in the 3d-future dataset. Since the origin 3d-future dataset only contains the `model_info.json` file, I just change the name of the file to enable the progress. Is my solution right ? Maybe I missed something.
> 
> Hi,
> 
> Thanks for pointing it out. I uploaded the `examples/datasets/front_3d_with_improved_mat/model_info_revised.json`, and updated the README. You basically need to move it to the 3D-FUTURE folder. Could you try again?
> 
> BTW, before you re-render a scene that failed once before, you need to delete it in the `failed_scene_names.txt`, which is automatically generated in `examples/datasets/front_3d_with_improved_mat`. This strategy is to skip bad scene cases that are not renderable.
> 
> Thanks

**Comment by qiisun** [comment]
Thanks a lot! Issue solved!

**Comment by kangx326** [comment]
> resources/cctextures/

Hi, I also met this problem. The error message is "list index out of range; Failed scene name: 6a0e73bc-d0c4-4a38-bfb6-e083ce05ebe9." Could you tell me how did you solve this?

**Comment by kangx326** [comment]
> * Bug in Single scene rendering
> 
> When I was run such script:
> 
> `CUDA_VISIBLE_DEVICES=4,5,6,7 \ blenderproc run \ examples/datasets/front_3d_with_improved_mat/render_dataset_improved_mat.py \ examples/datasets/front_3d_with_improved_mat/3D-FRONT \ examples/datasets/front_3d_with_improved_mat/3D-FUTURE-model \ examples/datasets/front_3d_with_improved_mat/3D-FRONT-texture \ 6a0e73bc-d0c4-4a38-bfb6-e083ce05ebe9.json \ resources/cctextures/ \ examples/datasets/front_3d_with_improved_mat/renderings`
> 
> Initially, there were no encounters with any bugs.
> 
> ![image](https://private-user-images.githubusercontent.com/55343765/253482728-277c37ed-fd7a-4fc9-b861-5c58b425962a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTY0MjEsIm5iZiI6MTcwMTg1NjEyMSwicGF0aCI6Ii81NTM0Mzc2NS8yNTM0ODI3MjgtMjc3YzM3ZWQtZmQ3YS00ZmM5LWI4NjEtNWM1OGI0MjU5NjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZGFlY2Q5OWY0MDNjM2NkNTZiMTI4NmU1NGUzZmRhMWI4NWFmMzlmZTQxMWQ5ZWE4NmVjYzAxMWFhMjE1OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZYfWllFgx-rnb-Bk14-566XxT95FibjD5Y6Z-jflPTI) ![image](https://private-user-images.githubusercontent.com/55343765/253482774-d38ae6d1-97f2-4b8d-b988-3694bf5d11cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTY0MjEsIm5iZiI6MTcwMTg1NjEyMSwicGF0aCI6Ii81NTM0Mzc2NS8yNTM0ODI3NzQtZDM4YWU2ZDEtOTdmMi00YjhkLWI5ODgtMzY5NGJmNWQxMWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZGU2OTcyNTA5NzM4OTFjMTgxZjcyOTRjMDk1YjNiNTU4N2IzZWE3YjBhMjI5M2Y0NzcxNDkyYzk0MTRkZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g1lbOwp0diIEcE5T1av6MSMcx-MRZ1AX9z7Oy5GcE5A) ![image](https://private-user-images.githubusercontent.com/55343765/253482860-5ab25e49-d3db-4500-82e9-3b6addbce378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTY0MjEsIm5iZiI6MTcwMTg1NjEyMSwicGF0aCI6Ii81NTM0Mzc2NS8yNTM0ODI4NjAtNWFiMjVlNDktZDNkYi00NTAwLTgyZTktM2I2YWRkYmNlMzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3Yjk1YjcwMTM0Y2U1NGRkM2NiNTVlMTM5MTczZTE3ZGUyY2NlZTc0ODAxN2NlZDU2NjQ3NTIwMGQ5NDRlMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zwyhDczlTONKiDFPduvWel_j9G1yXr5z2glADjb51B4)
> 
> ![image](https://private-user-images.githubusercontent.com/55343765/253482934-0879195f-63e5-4e83-ae50-781393a0d188.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTY0MjEsIm5iZiI6MTcwMTg1NjEyMSwicGF0aCI6Ii81NTM0Mzc2NS8yNTM0ODI5MzQtMDg3OTE5NWYtNjNlNS00ZTgzLWFlNTAtNzgxMzkzYTBkMTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkN2JjZDVjYjRmMmI4MzE4NzgzODM4YmVjYjkxMGQ3ZDgyYjYyYWFkZjM1NGY3ZTgyMDRkODgwZDdkOTE5ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6E4Sa_pk3ELg6ai22I8ykj_qw705-n5N7ZCtlLCTR5s)
> 
> But when the Fra: num==101 the code failed, I have no idea to deal with it. ![image](https://private-user-images.githubusercontent.com/55343765/253483186-57be1cdb-2115-419f-bd84-86b1060fd738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTY0MjEsIm5iZiI6MTcwMTg1NjEyMSwicGF0aCI6Ii81NTM0Mzc2NS8yNTM0ODMxODYtNTdiZTFjZGItMjExNS00MTlmLWJkODQtODZiMTA2MGZkNzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5NDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3MzVlNTk2ZGIzM2YxNWY5YzY2YTJhY2RkNDE3YmIwMTA4YjVkZTIwMDkwZTYwNDRkNjc1NjBiOThiNjZmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UXzwSyQWChI5cIMYXQ7vP-68Q6-k2Ax6sjDccxsD22s)

Hi, I also met a similar problem. The error message is "list index out of range; Failed scene name: 6a0e73bc-d0c4-4a38-bfb6-e083ce05ebe9." Could you tell me how to solve this?
![1701862517990](https://github.com/yinyunie/BlenderProc-3DFront/assets/35297996/10413b58-7d1f-4abb-bf10-85b383c23019)

**Comment by yinyunie** [comment]
it looks like the `cc_materials` list is empty. have you downloaded cc_materials by
```
blenderproc run blenderproc/scripts/download_cc_textures.py ./resources/cctextures
```

and after you have downloaded it, please delete the `failed_scene_names.txt` file under `examples/datasets/front_3d_with_improved_mat` and try again.

**Comment by kangx326** [comment]
> it looks like the `cc_materials` list is empty. have you downloaded cc_materials by
> 
> ```
> blenderproc run blenderproc/scripts/download_cc_textures.py ./resources/cctextures
> ```
> 
> and after you have downloaded it, please delete the `failed_scene_names.txt` file under `examples/datasets/front_3d_with_improved_mat` and try again.

 I've downloaded all the cc_materials following
> ```
> blenderproc run blenderproc/scripts/download_cc_textures.py ./resources/cctextures
> ``````
The same error still exists.
![1701863815105](https://github.com/yinyunie/BlenderProc-3DFront/assets/35297996/252f9a87-65a7-4c39-9253-46d8db2c55d0)

**Comment by yinyunie** [comment]
I would suggest you enter the 'debug' mode (please check [link](https://github.com/DLR-RM/BlenderProc#debugging-with-pycharm-professional)), and print out why [this line](https://github.com/yinyunie/BlenderProc-3DFront/blob/4cc055f1ce8342bf25bc11e116ab9ee36a5a277c/examples/datasets/front_3d_with_improved_mat/render_dataset_improved_mat.py#L146) outputs an empty list.

Best,
Yinyu

**Comment by kangx326** [comment]
> I would suggest you enter the 'debug' mode (please check [link](https://github.com/DLR-RM/BlenderProc#debugging-with-pycharm-professional)), and print out why [this line](https://github.com/yinyunie/BlenderProc-3DFront/blob/4cc055f1ce8342bf25bc11e116ab9ee36a5a277c/examples/datasets/front_3d_with_improved_mat/render_dataset_improved_mat.py#L146) outputs an empty list.
> 
> Best, Yinyu

Thank you for your advice. I found the reason for this error. In https://github.com/yinyunie/BlenderProc-3DFront/blob/4cc055f1ce8342bf25bc11e116ab9ee36a5a277c/blenderproc/python/loader/CCMaterialLoader.py#L69C65-L69C74  , the default image path is 'base_image_path = os.path.join(current_path, "{}_2K_Color.jpg".format(asset))'. However, the newly download material images are named as xxx_2K-JPG_Color.jpg. I modified this line as 'base_image_path = os.path.join(current_path, "{}_2K-JPG_Color.jpg".format(asset))' and solved this issue.
Thanks a lot.
