### ISSUE TITLE
[BUG]: How to render with a headless device?

### ISSUE THREAD

**Issue by linjing7** [yinyunie/BlenderProc-3DFront#4]
Hi, thanks for your excellent work! I'm wondering if it is possible to perform the rendering in a headless remote device. It would make it much more convenient to use your codebase as most people use the remote servers of schools and companies, which do not have a screen to display.

**Comment by yinyunie** [comment]
Hi,

X server is required for 3D visualization only (i.e., You can render on a remote headless server, and visualize the 3D contents interactively with your local machine).

Best,
Yinyu

**Comment by linjing7** [comment]
Okay, thanks for your reply.
